using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Shell32;

namespace DateYourPhotos
{
    public class ShellFileInfo
    {
        public enum infoFile : int
        {
            Nombre = 0,
            Tamanyo = 1,
            Tipo_de_elemento = 2,
            Fecha_de_modificacion = 3,
            Fecha_de_creacion = 4,
            Fecha_de_acceso = 5,
            Atributos = 6,
            Estado_sin_conexion = 7,
            Disponibilidad = 8,
            Tipo_percibido = 9,
            Propietario = 10,
            Clase = 11,
            Fecha_de_captura = 12,
            Interpretes_colaboradores = 13,
            Álbum = 14,
            Año = 15,
            Genero = 16,
            Conductores = 17,
            Etiquetas = 18,
            Clasificacion = 19,
            Autores = 20,
            Titulo = 21,
            Asunto = 22,
            Categorias = 23,
            Comentarios = 24,
            Copyright = 25,
            Numero_de_pista = 26,
            Duracion = 27,
            Velocidad_de_bits = 28,
            Modo_protegido = 29,
            Modelo_de_cámara = 30,
            Dimensiones = 31,
            Fabricante_de_camara = 32,
            Organizacion = 33,
            Descripcion_del_archivo = 34,
            Nombre_del_programa = 35,
            Duracion_de_evento = 36,
            Esta_conectado = 37,
            Recurrente = 38,
            Ubicación = 39,
            Direcciones_de_los_asistentes_opcionales = 40,
            Asistentes_opcionales = 41,
            Dirección_del_organizador = 42,
            Nombre_del_organizador = 43,
            Hora_de_aviso = 44,
            Direcciones_de_los_asistentes_obligatorios = 45,
            Asistentes_requeridos = 46,
            Recursos = 47,
            Estado_de_la_reunión = 48,
            Estado_de_disponible_ocupado = 49,
            Tamanyo_total = 50,
            Nombre_de_cuenta = 51,
            Estado_de_la_tarea = 52,
            Equipo = 53,
            Aniversario = 54,
            Nombre_del_asistente = 55,
            Telefono_del_asistente = 56,
            Cumpleanyos = 57,
            Direccion_del_trabajo = 58,
            Ciudad_de_trabajo = 59,
            Pais_o_region_de_trabajo = 60,
            Apartado_de_correos_de_trabajo = 61,
            Codigo_postal_del_trabajo = 62,
            Estado_o_provincia_del_trabajo = 63,
            Calle_del_trabajo = 64,
            Fax_del_trabajo = 65,
            Pagina_principal_del_trabajo = 66,
            Telefono_del_trabajo = 67,
            Numero_de_devolucion_de_llamada = 68,
            Telefono_del_automovil = 69,
            Hijos = 70,
            Teléfono_principal_de_la_organizacion = 71,
            Departamento = 72,
            Direccion_de_correo_electronico = 73,
            Correo_electronico_2 = 74,
            Correo_electronico_3 = 75,
            Lista_de_correos_electronicos = 76,
            Nombre_para_mostrar_de_correo_electronico = 77,
            Archivo_como = 78,
            Nombre_de_pila = 79,
            Nombre_completo = 80,
            Sexo = 81,
            Nombre_propio = 82,
            Aficiones = 83,
            Dirección_particular = 84,
            Ciudad_del_domicilio = 85,
            Pais_o_region_del_domicilio = 86,
            Apartado_de_correos_del_domicilio = 87,
            Código_postal_del_domicilio = 88,
            Estado_o_provincia_del_domicilio = 89,
            Calle_del_domicilio = 90,
            Fax_particular = 91,
            Telefono_particular = 92,
            Direcciones_de_mensajeria_instantanea = 93,
            Iniciales = 94,
            Puesto = 95,
            Etiqueta = 96,
            Apellidos = 97,
            Dirección_de_correo = 98,
            Segundo_nombre = 99,
            Telefono_celular = 100,
            Alias = 101,
            Ubicación_de_la_oficina = 102,
            Otra_direccion = 103,
            Otra_ciudad = 104,
            Otro_pais_o_region = 105,
            Otro_apartado_postal = 106,
            Otro_codigo_postal = 107,
            Otro_estado_o_provincia = 108,
            Otra_calle = 109,
            Buscapersonas = 110,
            Tratamiento_personal = 111,
            Ciudad = 112,
            Pais_o_región = 113,
            Apartado_de_correos = 114,
            Codigo_postal = 115,
            Estado_o_provincia = 116,
            Calle = 117,
            Correo_electronico_principal = 118,
            Teléfono_principal = 119,
            Profesion = 120,
            Conyuge_companyero = 121,
            Sufijo = 122,
            Telefono_TTY_TTD = 123,
            Telex = 124,
            Pagina_web = 125,
            Estado_de_contenido = 126,
            Tipo_de_contenido = 127,
            Fecha_de_adquisicion = 128,
            Fecha_de_archivado = 129,
            Fecha_en_que_se_completo = 130,
            Categoria_del_dispositivo = 131,
            Conectado = 132,
            Metodo_de_deteccion = 133,
            Nombre_descriptivo = 134,
            Equipo_local = 135,
            Fabricante = 136,
            Modelo = 137,
            Emparejado = 138,
            Clasificacion_2 = 139,
            Estado_1 = 140,
            Estado_2 = 141,
            Id_de_cliente = 142,
            Contribuyentes = 143,
            Contenido_creado = 144,
            Fecha_de_impresion = 145,
            Guardado_el = 146,
            Division = 147,
            Id_de_documento = 148,
            Paginas = 149,
            Diapositivas = 150,
            Tiempo_de_edicion = 151,
            Contar_palabras = 152,
            Fecha_de_vencimiento = 153,
            Fecha_de_finalización = 154,
            Recuento_de_archivos = 155,
            Extensión_del_archivo = 156,
            Nombre_de_archivo = 157,
            Versión_del_archivo = 158,
            Color_de_la_marca = 159,
            Estado_del_marcador = 160,
            Espacio_disponible = 161,
            Vacio_1 = 162,
            Vacio_2 = 163,
            Tipo_para_compartir = 164,
            Profundidad_en_bits = 165,
            Resolucion_horizontal = 166,
            Ancho = 167,
            Resolucion_vertical = 168,
            Alto = 169,
            Importancia = 170,
            Es_un_dato_adjunto = 171,
            Se_elimino = 172,
            Estado_de_cifrado = 173,
            Tiene_un_marcador = 174,
            Esta_completado = 175,
            Incompleto = 176,
            Estado_de_lectura = 177,
            Compartido = 178,
            Creadores = 179,
            Fecha = 180,
            Nombre_de_carpeta = 181,
            Ruta_de_acceso_a_la_carpeta = 182,
            Carpeta = 183,
            Participantes = 184,
            Ruta_de_acceso = 185,
            Por_ubicacion = 186,
            Tipo = 187,
            Nombre_de_contacto = 188,
            Tipo_de_entrada = 189,
            Idioma = 190,
            Fecha_de_visita = 191,
            Descripcion = 192,
            Estado_de_vinculo = 193,
            Vincular_destino = 194,
            Dirección_URL = 195,
            Vacio_3 = 196,
            Medio_creado = 197,
            Fecha_de_lanzamiento = 198,
            Codificado_por = 199,
            Número_de_episodio = 200,
            Productores = 201,
            Editor = 202,
            Numero_de_temporada = 203,
            Subtitulo = 204,
            Direccion_URL_del_usuario = 205,
            Editores = 206,
            Vacio_4 = 207,
            Datos_adjuntos = 208,
            Direcciones_CCO = 209,
            CCO = 210,
            Direcciones_CC = 211,
            CC = 212,
            Id_de_conversacion = 213,
            Fecha_de_recepcion = 214,
            Fecha_de_envio = 215,
            Direcciones_de_remitentes = 216,
            De = 217,
            Tiene_datos_adjuntos = 218,
            Direccion_del_remitente = 219,
            Nombre_del_remitente = 220,
            Almacen = 221,
            Direccion_del_destinatario = 222,
            Título_de_tareas_pendientes = 223,
            Para = 224,
            Kilometraje = 225,
            Interprete_del_album = 226,
            Ordenar_por_interprete_del_album = 227,
            Id_de_album = 228,
            Ordenar_por_album = 229,
            Ordenar_por_interpretes_colaboradores = 230,
            Pulsaciones_por_minuto = 231,
            Compositores = 232,
            Ordenar_por_compositor = 233,
            Clave_inicial = 234,
            Parte_de_una_compilacion = 235,
            Estilo_de_musica = 236,
            Parte_del_conjunto = 237,
            Periodo = 238,
            Color = 239,
            Clasificacion_parental = 240,
            Motivo_de_clasificacion_parental = 241,
            Espacio_usado = 242,
            Versión_EXIF = 243,
            Evento = 244,
            Compensacion_de_exposicion = 245,
            Programacion_de_exposicion = 246,
            Tiempo_de_exposicion = 247,
            Punto_F = 248,
            Modo_de_flash = 249,
            Distancia_focal = 250,
            Longitud_focal_de_35_mm = 251,
            Velocidad_ISO = 252,
            Creador_de_objetivo = 253,
            Modelo_de_objetivo = 254,
            Fuente_de_luz = 255,
            Apertura_maxima = 256,
            Modo_de_medicion = 257,
            Orientacion = 258,
            Personas = 259,
            Modo_de_programa = 260,
            Saturacion = 261,
            Distancia_al_objeto = 262,
            Balance_de_blanco = 263,
            Prioridad = 264,
            Proyecto = 265,
            Número_de_canal = 266,
            Episodio = 267,
            Subtítulos_CC = 268,
            Repeticion = 269,
            SAP = 270,
            Fecha_de_difusion = 271,
            Descripcion_2 = 272,
            Grabado_el = 273,
            Senyal_de_identificacion_de_la_cadena_de_television = 274,
            Nombre_de_cadena_de_television = 275,
            Resumen = 276,
            Fragmentos = 277,
            Resumen_automatico = 278,
            Clasificación_de_la_busqueda = 279,
            Caracter = 280,
            Compartido_con = 281,
            Estado_de_uso_compartido = 282,
            Vacio_5 = 283,
            Nombre_producto = 284,
            Version_producto = 285,
            Vinculo_de_soporte_tecnico = 286,
            Origen = 287,
            Fecha_de_inicio = 288,
            Compartiendose = 289,
            Informacion_de_facturacion = 290,
            Completa = 291,
            Propietario_de_la_tarea = 292,
            Ordenar_por_titulo = 293,
            Tamaño_total_del_archivo = 294,
            Marcas_comerciales = 295,
            Compresion_de_video = 296,
            Directores = 297,
            Velocidad_de_datos = 298,
            Alto_fotograma = 299,
            Velocidad_fotograma = 300,
            Ancho_fotograma = 301,
            Orientacion_de_video = 302,
            Velocidad_de_bits_total = 303
        }

        public ShellFileInfo() { }

        public string GetFileDetails(string fileFolder, string filePath, infoFile infotype)
        {
            try
            {
                Shell fileshell = new Shell();
                Folder fileshellfolder = fileshell.NameSpace(fileFolder);
                return fileshellfolder.GetDetailsOf(fileshellfolder.ParseName(filePath), (int)infotype);
            }
            catch
            {
                return string.Empty;
            }
        }

        public Dictionary<string,string> GetFileDetails(string fileFolder, string filePath)
        {
            Dictionary<string,string> arrHeaders = new Dictionary<string,string>();

            Shell shell = new Shell32.Shell();
            Folder fileshellfolder = shell.NameSpace(fileFolder);

            for (int i = 0; i <= 303; i++)
            {
                try
                {
                    arrHeaders.Add(((infoFile)i).ToString(), fileshellfolder.GetDetailsOf(fileshellfolder.ParseName(filePath), i));
                }
                catch { }
            }

            return arrHeaders;
        }
    }
}
